### PR TITLE
allow 300 barcodes

### PR DESCRIPTION
**Pull request by luciipak**

### CODE REVIEW

**Review by tannermpeterson — COMMENTED** [review]
We should still try to get the pulse3d fix in

**Comment by luciipak** [comment]
> We should still try to get the pulse3d fix in

that'll have to be done separately, just posted the PR for that. I'll add 0.33.10 into K8s

**Comment by tannermpeterson** [comment]
The amplitude in live view will be incorrect until we bring pulse3d 0.33.11 into the MA Controller

**Comment by luciipak** [comment]
> The amplitude in live view will be incorrect until we bring pulse3d 0.33.11 into the MA Controller

Oh duh, yeah forgot it's a dependency in this repo

**Review by tannermpeterson — APPROVED** [review]

**Pull request merged**
